name: Go CI

on:
  workflow_call:
    inputs:
      go-version:
        description: "Versao do Go utilizada pelo microsservico"
        required: false
        type: string
        default: "1.21"

jobs:
  build-test:
    name: Build and Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Build application
        run: go build ./...

      - name: Run unit tests
        run: go test ./...

  lint:
    name: Linter
    runs-on: ubuntu-latest
    needs: build-test
    continue-on-error: true

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  Security:
      name: Security Scan (SAST & SCA)
      runs-on: ubuntu-latest
      needs: build-test

      steps:
        - name: Checkout source code
          uses: actions/checkout@v4

       
        - name: Run Gosec Security Scanner
          continue-on-error: true
          uses: securego/gosec@master
          with:
            args: -severity high ./...

        - name: Run Trivy vulnerability scanner in fs mode
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: 'fs'
            scan-ref: '.'
            format: 'table'
            exit-code: '1' 
            severity: 'CRITICAL'